config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :flats do
    resources :bookings, only: [:new, :create]
  end

  root to: 'flats#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flat

  validates :booked_from, :booked_untill, presence: true
end

app/models/flat.rb
class Flat < ApplicationRecord
  has_many :bookings, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController

  before_action :set_flat, only: [:show, :edit, :update, :destroy]

  def index
    if params[:query].present?
      @flats = Flat.where("name LIKE ?", "%#{params[:query]}%")
    else
      @flats = Flat.all
    end
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to @flat
    else
      render :new
    end
  end

  def show
    @flat = Flat.find(params[:id])
    @booking = Booking.new
  end

  def edit
  end

  def update
  end

  def destroy 
    @flat.destroy
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end

  def set_flat
    @flat = Flat.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    respond_to do |format|
      format.html { redirect_to flats_url, alert: 'Flat not found.' }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<div class="container">
  <div>
    <%= simple_form_for @flat do |f| %>
      <%= f.input :name, class: "form-control" %>
      <%= f.input :address, class: "form-control" %>
      <%= f.input :description, class: "form-control" %>
      <%= f.input :price_per_night, class: "form-control" %>
      <%= f.input :number_of_guests, class: "form-control" %>
      <div class="d-flex justify-content-between">
        <%= f.submit class: "btn btn-primary" %>
        <%= link_to 'Back', flat_path(@flat), class: "btn btn-secondary"%>
      </div>
    <% end %>
  </div>
</div>

app/views/flats/index.html.erb
<div class="container-flats">
  <h1 class="mb-4">All our flats (<%= @flats.length%>)</h1>
  <div class="d-flex justify-content-center">
    <div class="row justify-content-center">
      <% @flats.each do |flat|%>
        <div class="col-3">
          <div class="flat-card border m-2">
            <img src="<%= flat.picture_url %>" class="card-img-top" alt="<%= flat.name %>">
            <div class="flat-card-body">
              <div class="title-flat">
                <h3><%= flat.name %></h3>
              </div>
              <h4>Local: <%= flat.address %></h4>
              <div class="d-flex justify-content-between">
                <div class="d-flex align-items-center guests">
                  <i class="fa-solid fa-user-group"></i>
                  <div class="guests_number"><%= flat.number_of_guests %></div>
                </div>
                <div class="d-flex align-items-center price">
                  <i class="fa-solid fa-yen-sign"></i>
                  <div class="price_value"><%= flat.price_per_night %></div>
                </div>
              </div>
            </div>
            <div class="details-flat d-flex justify-content-between">
              <%= link_to 'See Details', flat_path(flat)%>
              <div class="d-flex edit-btn">
                <%= button_to flat_path(flat), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn-flats" do %>
                  <i class="fa-solid fa-trash-can" style="color: #dc3545;"></i>
                <% end %>
                <%= link_to edit_flat_path(flat) do %>
                  <i class="fa-regular fa-pen-to-square" style="color: #0aa2c0;"></i>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<style></style>

app/views/flats/show.html.erb
<div class="flat-show">
  <div class="container flat-container">
    <div class="d-flex row">
      <div class="col-8">
        <div class="box-details mb-4">
          <h2><%= @flat.name %></h2>
          <h4>Local: <%= @flat.address %></h4>
        </div>
        <div class="box-details mb-4">
          <h3>More about this flat...</h3>
          <p><%= @flat.description %></p>
        </div>
        <div class="box-details mb-4">
          <h3>Details:</h3>
          <div class="d-flex justify-content-around">
            <div class="d-flex align-items-center guests">
              <p>Capacity:</p>
              <i class="fa-solid fa-user-group ms-4"></i>
              <div class="guests_number"><%= @flat.number_of_guests %></div>
            </div>
            <div class="d-flex align-items-center price">
              <p>Price per night:</p>
              <i class="fa-solid fa-yen-sign ms-4"></i>
              <div class="price_value"><%= @flat.price_per_night %></div>
            </div>
          </div>
        </div>
        <div class="d-flex justify-content-between">
          <div class="d-flex edit-btn">
            <%= link_to edit_flat_path(@flat) do %>
              <i class="fa-regular fa-pen-to-square" style="color: #0aa2c0"></i>
            <% end %>
            <%= button_to flat_path(@flat), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn-flats" do %>
              <i class="fa-solid fa-trash-can" style="color: #dc3545;"></i>
            <% end %>
          </div>
          <%= link_to 'Back to All Flats', flats_path, class: "btn btn-secondary"%>
        </div>
      </div>
      <div class="col">
        <div class="box-details">
          <h3>Book this place!</h3>
          <%= simple_form_for [@flat, @booking], html: { class: 'form-horizontal' }, local: true do |form| %>
            <div class="ms-4">
              <div class="form-group">
                <%= form.label :booked_from, "Start Date", class: "control-label mt-2" %>
                <div class="col-sm-10">
                  <%= form.date_field :booked_from, class: "form-control" %>
                </div>
              </div>
              <div class="form-group">
                <%= form.label :booked_until, "End Date", class: "control-label mt-2" %>
                <div class="col-sm-10">
                  <%= form.date_field :booked_until, class: "form-control" %>
                </div>
              </div>
              <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                  <%= form.submit "Book", class: "btn btn-primary mt-4" %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
        <div class="box-details mt-4">
          <h3>Share</h3>
          <div class="d-flex social-media justify-content-around my-4">
            <i class="fa-brands fa-square-facebook"></i>
            <i class="fa-brands fa-square-instagram"></i>
            <i class="fa-brands fa-square-twitter"></i>
            <i class="fa-solid fa-envelope"></i>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<style>
  .flat-show {
    background-image: url('<%= @flat.picture_url %>');
    width: 100%;
    height: 500px;
    background-size: cover;
    background-position: center;
    background-repeat: no-repeat;
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .flat-container {
    margin-top: 500px;
  }
  .box-details {
    background: #eff1f4;
    border-radius: 4px;
    padding: 1rem;
    box-shadow: 1px 1px 4px rgba(0, 0, 0, 0.2);
  }

  .box-details h4 {
    color: #6c757d;
    font-size: 1.2rem;
  }

  .box-details p {
    font-size: 1.2rem;
    margin-top: 1rem;
  }

  .social-media i {
    font-size: 3rem;
    color: #0aa2c0;
  }
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  </head>
  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <% flash.each do |key, value| %>
      <div class="flash <%= key %>"><%= value %></div>
    <% end %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to root_path do %>
      <i class="fa-brands fa-airbnb"></i>
    <% end %>
    <div class="d-flex">
      <%= form_with(url: flats_path, method: :get, local: true, class: "d-flex ms-2") do %>
        <%= text_field_tag :query, params[:query], class: "form-control me-2", placeholder: "Search flats" %>
        <%= submit_tag "Search", class: "btn btn-outline-success my-2 my-sm-0" %>
      <% end %>
      <%= link_to 'Add Flat', new_flat_path, class: "ms-2 btn btn-info"%>
    </div>
  </div>
</nav>
<style>
  nav {
    padding: 50px;
    background: #e9ecef;
  }

  nav i {
    font-size: 3rem;
  }
</style>